"""Executive PDF report for Competitive Insights (Entregable 2.2).

Consumes the JSON payloads generated by generate_analysis.py and
produces a multi-section PDF with KPIs, insights, and visual evidence.
"""

from __future__ import annotations

import argparse
import json
from datetime import datetime
from pathlib import Path
from typing import Dict, List

from reportlab.lib import colors
from reportlab.lib.enums import TA_CENTER, TA_JUSTIFY
from reportlab.lib.pagesizes import A4
from reportlab.lib.styles import ParagraphStyle, getSampleStyleSheet
from reportlab.lib.units import cm
from reportlab.pdfgen import canvas as pdfcanvas
from reportlab.platypus import (
    HRFlowable,
    Image,
    KeepTogether,
    PageBreak,
    Paragraph,
    SimpleDocTemplate,
    Spacer,
    Table,
    TableStyle,
)

OUTPUT_PDF = Path("output/Competitive_Intelligence_Rappi_MX.pdf")
MARGIN = 1.8 * cm
RAPPI_RED = colors.HexColor("#FF441F")
DARK = colors.HexColor("#0D0F1F")
LIGHT_BG = colors.HexColor("#F4F5FB")
TEXT = colors.HexColor("#1A1A2E")
ACCENT = colors.HexColor("#5B8EF0")

# Chart descriptions for the PDF - explain purpose and interpretation
CHART_DESCRIPTIONS = {
    "chart_eta_by_zone": {
        "title": "ETA promedio por zona",
        "purpose": "Compara el tiempo de entrega estimado (ETA = minutos prometidos en la app) de cada plataforma en cada zona geográfica. "
                   "La línea roja punteada marca el SLA interno de 30 minutos.",
        "relevance": "Para el equipo de Operations: identifica zonas donde Rappi pierde competitividad en velocidad. "
                     "Para Strategy: zonas con ETA alto pueden requerir subsidios a repartidores o alianzas con dark kitchens.",
    },
    "chart_rating_by_city": {
        "title": "Rating del restaurante por ciudad y plataforma",
        "purpose": "Muestra la calificación promedio de McDonald's en cada plataforma por ciudad (escala 3-5). "
                   "El rating refleja la percepción del usuario sobre la experiencia de pedido.",
        "relevance": "Un rating bajo en Rappi vs competencia puede indicar problemas de empaque, tiempos de entrega o atención al cliente. "
                     "El equipo de Quality debe investigar las ciudades con mayor brecha.",
    },
    "chart_promo_hook_by_zone": {
        "title": "Promo hook por zona (%)",
        "purpose": "El promo hook es el porcentaje de descuento visible en la tarjeta del restaurante dentro del feed de la app. "
                   "Es el primer gancho que ve el usuario antes de entrar al menú.",
        "relevance": "Para Pricing: la visibilidad del descuento en el feed es el driver #1 de click-through rate (CTR). "
                     "Si la competencia muestra hooks más altos, Rappi pierde visibilidad.",
    },
    "chart_promo_distribution": {
        "title": "Distribución de promo % (boxplot)",
        "purpose": "Resume el rango mínimo-mediana-máximo del promo hook por plataforma. "
                   "Permite ver la dispersión y agresividad de cada competidor.",
        "relevance": "Una mediana alta con rango estrecho indica estrategia consistente. "
                     "Un rango amplio sugiere promociones variables por zona (oportunidad de arbitraje).",
    },
    "chart_bigmac_price_positioning": {
        "title": "Combo Big Mac: precio original vs con promo",
        "purpose": "Compara el precio base y el precio con descuento aplicado del Combo Big Mac Mediano en cada plataforma.",
        "relevance": "Para Pricing: el Big Mac es un benchmark universal. Si Rappi es consistentemente más caro, "
                     "el usuario lo percibe y migra. La brecha entre base y promo indica la profundidad del descuento.",
    },
    "chart_service_fee_by_zone": {
        "title": "Service fee estimado por zona",
        "purpose": "Service fee = comisión que cobra la app al usuario sobre el subtotal. "
                   "Estimado con tasas fijas: Rappi 10%, Uber Eats 15%, DiDi Food 8%.",
        "relevance": "Para Pricing: el service fee es un componente oculto pero impacta el ticket final. "
                     "DiDi tiene la tasa más baja, lo que explica parte de su ventaja en precio total.",
    },
    "chart_total_price_by_zone": {
        "title": "Total estimado al usuario por zona",
        "purpose": "Suma de subtotal + delivery fee + service fee. Es lo que el usuario ve en el checkout antes de pagar. "
                   "Representa la percepción real de costo.",
        "relevance": "Para Strategy: el total percibido define la elección de plataforma. "
                     "Una brecha >5% desplaza market share hacia el competidor más barato.",
    },
    "chart_eta_vs_promo_scatter": {
        "title": "Scatter: ¿compensan tardanza con descuento?",
        "purpose": "Cada punto es una observación zona-plataforma. Eje X = ETA (minutos), Eje Y = promo hook (%). "
                   "Busca correlación entre velocidad y agresividad promocional.",
        "relevance": "Si una plataforma ofrece ETAs altos pero promos altas, compensa con precio. "
                     "Si tiene ETA alto sin promo, es una debilidad explotable.",
    },
    "chart_eta_heatmap": {
        "title": "Heatmap de ETA por zona (verde = más rápido)",
        "purpose": "Matriz de calor que muestra el ETA promedio de cada plataforma en cada zona. "
                   "Verde indica tiempos más rápidos, rojo indica tiempos más lentos.",
        "relevance": "Para Operations: identifica de un vistazo las zonas donde Rappi es más lento que la competencia "
                     "y necesita reforzar la flota de repartidores.",
    },
    "chart_price_heatmap": {
        "title": "Heatmap de precio Big Mac con descuento",
        "purpose": "Matriz de calor del precio efectivo (con descuento aplicado) del Combo Big Mac por zona y plataforma. "
                   "Colores más oscuros = precio más alto.",
        "relevance": "Para Pricing: permite ver en qué zonas Rappi es el más caro del mercado y dónde tiene ventaja. "
                     "Las zonas en rojo para Rappi son prioridad de ajuste.",
    },
    "chart_delivery_fee_comparison": {
        "title": "Delivery fee por zona y plataforma",
        "purpose": "Compara cuánto cobra cada plataforma por el envío en cada zona geográfica. "
                   "El delivery fee es un componente visible y sensible para el usuario.",
        "relevance": "Para Pricing: si Rappi cobra delivery fees más altos en zonas periféricas, pierde competitividad "
                     "justo donde necesita crecer. Considerar subsidios selectivos.",
    },
    "chart_wealthy_vs_nonwealthy": {
        "title": "Variabilidad geográfica: Wealthy vs Non Wealthy",
        "purpose": "Compara 4 métricas clave (total, ETA, delivery fee, promo) entre zonas de alto y bajo nivel socioeconómico "
                   "para cada plataforma.",
        "relevance": "Para Strategy: si la competitividad varía por tipo de zona, los equipos de Pricing y Growth "
                     "deben ajustar estrategias diferenciadas. Las zonas Non Wealthy son clave para expansión.",
    },
    "chart_three_products_comparison": {
        "title": "Comparativa de precios: 3 productos clave",
        "purpose": "Compara precios base vs con promo de los 3 productos monitoreados: Combo Big Mac Mediano, "
                   "Hamburguesa Doble con Queso, y Coca-Cola Mediana en cada plataforma.",
        "relevance": "Para Pricing: permite detectar si la competencia subsidia ciertos productos como gancho. "
                     "Si DiDi descuenta agresivamente el Big Mac pero no la Coca-Cola, es una estrategia de anchor pricing.",
    },
    "chart_total_cost_breakdown": {
        "title": "Desglose del costo total por plataforma",
        "purpose": "Descompone el ticket promedio en sus 3 componentes: subtotal de productos, delivery fee y service fee. "
                   "Muestra qué proporción del costo final corresponde a cada concepto.",
        "relevance": "Para Pricing y Strategy: revela si la ventaja de precio de un competidor viene de productos más baratos, "
                     "delivery fee subsidizado, o service fee más bajo. Cada palanca requiere una respuesta distinta.",
    },
}


class NumberedCanvas(pdfcanvas.Canvas):
    """Adds footer with page numbers and confidentiality banner."""

    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        self._pages = []

    def showPage(self):
        self._pages.append(dict(self.__dict__))
        self._startPage()

    def save(self):
        total = len(self._pages)
        for state in self._pages:
            self.__dict__.update(state)
            if self._pageNumber > 1:
                self.setFont("Helvetica", 7)
                self.setFillColor(colors.HexColor("#6F7391"))
                self.drawRightString(A4[0] - MARGIN, 1.0 * cm, f"Pag. {self._pageNumber}/{total}")
                self.drawString(MARGIN, 1.0 * cm, "CONFIDENCIAL · Competitive Intelligence Rappi")
                self.setStrokeColor(colors.HexColor("#D7DAE7"))
                self.setLineWidth(0.4)
                self.line(MARGIN, 1.3 * cm, A4[0] - MARGIN, 1.3 * cm)
            super().showPage()
        super().save()


def cover_page(canvas, doc):
    canvas.saveState()
    canvas.setFillColor(DARK)
    canvas.rect(0, 0, A4[0], A4[1], stroke=0, fill=1)
    canvas.setFillColor(RAPPI_RED)
    canvas.rect(0, A4[1] * 0.6, A4[0], A4[1] * 0.4, stroke=0, fill=1)

    canvas.setFillColor(colors.white)
    canvas.setFont("Helvetica-Bold", 34)
    canvas.drawString(MARGIN, A4[1] - 2.8 * cm, "RAPPI")
    canvas.setFont("Helvetica-Bold", 26)
    canvas.drawString(MARGIN, A4[1] - 4.5 * cm, "Competitive Intelligence")
    canvas.setFont("Helvetica", 16)
    canvas.drawString(MARGIN, A4[1] - 5.8 * cm, "Informe 2.2 · Insights Accionables")

    canvas.setFont("Helvetica", 12)
    canvas.setFillColor(colors.HexColor("#FFE9E0"))
    canvas.drawString(MARGIN, A4[1] - 7.4 * cm, f"Generado: {datetime.now().strftime('%d %b %Y')}")

    canvas.setFillColor(colors.HexColor("#0F111C"))
    canvas.rect(0, 0, A4[0], 5.5 * cm, stroke=0, fill=1)
    canvas.setFillColor(colors.white)
    canvas.setFont("Helvetica-Bold", 12)
    canvas.drawString(MARGIN, 4 * cm, "Rappi vs Uber Eats vs DiDi Food")
    canvas.setFont("Helvetica", 10)
    canvas.drawString(MARGIN, 3 * cm, "Fuente: scraping McDonald's · precios, fees, ETA y promos")
    canvas.drawString(MARGIN, 2.2 * cm, "Service fee estimado = subtotal x tasa fija (R 10 %, U 15 %, D 8 %)")
    canvas.restoreState()


def load_payloads(output_dir: Path) -> Dict:
    kpis_path = output_dir / "kpis.json"
    insights_path = output_dir / "top_insights.json"
    if not kpis_path.exists():
        raise FileNotFoundError("Ejecuta generate_analysis.py antes de armar el PDF")
    with kpis_path.open(encoding="utf-8") as fh:
        kpis = json.load(fh)
    insights = []
    if insights_path.exists():
        with insights_path.open(encoding="utf-8") as fh:
            payload = json.load(fh)
            insights = payload.get("insights", [])
    return kpis, insights


def build_styles() -> Dict[str, ParagraphStyle]:
    styles = getSampleStyleSheet()
    styles.add(ParagraphStyle("TitleSmall", parent=styles["Heading1"], fontSize=15, textColor=TEXT))
    styles.add(ParagraphStyle("Section", parent=styles["Heading2"], fontSize=12, textColor=TEXT, spaceBefore=14, spaceAfter=6))
    styles.add(ParagraphStyle("Body", parent=styles["BodyText"], fontSize=10, leading=14, textColor=TEXT, alignment=TA_JUSTIFY))
    styles.add(ParagraphStyle("Note", parent=styles["BodyText"], fontSize=8.5, textColor=colors.HexColor("#666A86")))
    styles.add(ParagraphStyle("InsightTitle", fontName="Helvetica-Bold", fontSize=11, textColor=RAPPI_RED))
    styles.add(ParagraphStyle("InsightSub", fontName="Helvetica", fontSize=9.3, leading=13, textColor=TEXT))
    styles.add(ParagraphStyle("Caption", alignment=TA_CENTER, fontSize=8.5, textColor=colors.HexColor("#6C6F85")))
    styles.add(ParagraphStyle("ChartPurpose", fontName="Helvetica", fontSize=8.5, leading=12,
                               textColor=colors.HexColor("#3A3D5C"), spaceBefore=4, spaceAfter=2))
    styles.add(ParagraphStyle("ChartRelevance", fontName="Helvetica-Oblique", fontSize=8.5, leading=12,
                               textColor=colors.HexColor("#5B6080"), spaceBefore=2, spaceAfter=6))
    styles.add(ParagraphStyle("GlossaryTerm", fontName="Helvetica-Bold", fontSize=9, textColor=TEXT))
    styles.add(ParagraphStyle("GlossaryDef", fontName="Helvetica", fontSize=8.5, leading=12,
                               textColor=colors.HexColor("#4A4D66"), spaceAfter=4))
    return styles


def platform_table(kpis: Dict, styles) -> Table:
    platforms = kpis["platforms"]
    header = ["Métrica"] + [stats["label"] for stats in platforms.values()]
    rows = [header]

    def fmt(val, suffix=""):
        return "N/D" if val is None else f"{val:.0f}{suffix}"

    def fmt1(val, suffix=""):
        return "N/D" if val is None else f"{val:.1f}{suffix}"

    rows.append(["ETA promedio (min)"] + [fmt(stats.get("eta_avg"), " min") for stats in platforms.values()])
    rows.append(["Rating McDonald's"] + [fmt1(stats.get("rating_avg")) for stats in platforms.values()])
    rows.append(["Promo hook promedio"] + [fmt(stats.get("promo_hook_avg"), "%") for stats in platforms.values()])
    rows.append(["Combo Big Mac (con promo)"] + [fmt(stats.get("bm_price_avg"), " MXN") for stats in platforms.values()])
    rows.append(["Hamburguesa Doble c/ Queso"] + [fmt(stats.get("hdq_price_avg"), " MXN") for stats in platforms.values()])
    rows.append(["Coca-Cola Mediana"] + [fmt(stats.get("cc_price_avg"), " MXN") for stats in platforms.values()])
    rows.append(["Delivery fee promedio"] + [fmt(stats.get("delivery_fee_avg"), " MXN") for stats in platforms.values()])
    rows.append(["Service fee (modelo)"] + [fmt(stats.get("service_fee_model_avg"), " MXN") for stats in platforms.values()])
    rows.append(["Subtotal promedio"] + [fmt(stats.get("subtotal_avg"), " MXN") for stats in platforms.values()])
    rows.append(["Total estimado"] + [fmt(stats.get("total_avg"), " MXN") for stats in platforms.values()])
    rows.append(["Cobertura % (success)"] + [fmt(stats.get("coverage_pct"), "%") for stats in platforms.values()])

    table = Table(rows, repeatRows=1)
    table.setStyle(TableStyle([
        ("BACKGROUND", (0, 0), (-1, 0), RAPPI_RED),
        ("TEXTCOLOR", (0, 0), (-1, 0), colors.white),
        ("FONTNAME", (0, 0), (-1, 0), "Helvetica-Bold"),
        ("FONTSIZE", (0, 0), (-1, 0), 10),
        ("ALIGN", (0, 0), (-1, 0), "CENTER"),
        ("ROWBACKGROUNDS", (0, 1), (-1, -1), [colors.white, LIGHT_BG]),
        ("TEXTCOLOR", (0, 1), (-1, -1), TEXT),
        ("FONTNAME", (0, 1), (-1, -1), "Helvetica"),
        ("FONTSIZE", (0, 1), (-1, -1), 9),
        ("ALIGN", (1, 1), (-1, -1), "CENTER"),
        ("ALIGN", (0, 1), (0, -1), "LEFT"),
        ("INNERGRID", (0, 0), (-1, -1), 0.4, colors.HexColor("#CCD0E0")),
        ("BOX", (0, 0), (-1, -1), 0.6, colors.HexColor("#B6BACB")),
    ]))
    return table


def wealthy_comparison_table(kpis: Dict, styles) -> Table:
    """Table comparing Wealthy vs Non Wealthy metrics per platform."""
    platforms = kpis["platforms"]
    header = ["Métrica"] + [stats["label"] for stats in platforms.values()]
    rows = [header]

    def fmt(val, suffix=""):
        return "N/D" if val is None else f"{val:.0f}{suffix}"

    rows.append(["Total Wealthy"] + [fmt(s.get("wealthy_total_avg"), " MXN") for s in platforms.values()])
    rows.append(["Total Non Wealthy"] + [fmt(s.get("non_wealthy_total_avg"), " MXN") for s in platforms.values()])
    rows.append(["ETA Wealthy"] + [fmt(s.get("wealthy_eta_avg"), " min") for s in platforms.values()])
    rows.append(["ETA Non Wealthy"] + [fmt(s.get("non_wealthy_eta_avg"), " min") for s in platforms.values()])
    rows.append(["Delivery Fee Wealthy"] + [fmt(s.get("wealthy_delivery_fee_avg"), " MXN") for s in platforms.values()])
    rows.append(["Delivery Fee Non Wealthy"] + [fmt(s.get("non_wealthy_delivery_fee_avg"), " MXN") for s in platforms.values()])

    table = Table(rows, repeatRows=1)
    table.setStyle(TableStyle([
        ("BACKGROUND", (0, 0), (-1, 0), ACCENT),
        ("TEXTCOLOR", (0, 0), (-1, 0), colors.white),
        ("FONTNAME", (0, 0), (-1, 0), "Helvetica-Bold"),
        ("FONTSIZE", (0, 0), (-1, 0), 10),
        ("ALIGN", (0, 0), (-1, 0), "CENTER"),
        ("ROWBACKGROUNDS", (0, 1), (-1, -1), [colors.white, LIGHT_BG]),
        ("TEXTCOLOR", (0, 1), (-1, -1), TEXT),
        ("FONTNAME", (0, 1), (-1, -1), "Helvetica"),
        ("FONTSIZE", (0, 1), (-1, -1), 9),
        ("ALIGN", (1, 1), (-1, -1), "CENTER"),
        ("ALIGN", (0, 1), (0, -1), "LEFT"),
        ("INNERGRID", (0, 0), (-1, -1), 0.4, colors.HexColor("#CCD0E0")),
        ("BOX", (0, 0), (-1, -1), 0.6, colors.HexColor("#B6BACB")),
    ]))
    return table


def availability_table(kpis: Dict) -> Table:
    data = [["Plataforma", "Success", "Partial", "Fail/No store", "restaurant_available=False"]]
    for plat, stats in kpis["availability"].items():
        status = stats.get("statuses", {})
        data.append([
            stats["label"],
            status.get("success", 0),
            status.get("partial", 0),
            status.get("partial_no_store", 0) + status.get("fail", 0),
            stats.get("restaurant_unavailable", 0),
        ])
    table = Table(data, repeatRows=1)
    table.setStyle(TableStyle([
        ("BACKGROUND", (0, 0), (-1, 0), colors.HexColor("#1E2130")),
        ("TEXTCOLOR", (0, 0), (-1, 0), colors.white),
        ("FONTNAME", (0, 0), (-1, 0), "Helvetica-Bold"),
        ("ROWBACKGROUNDS", (0, 1), (-1, -1), [colors.white, LIGHT_BG]),
        ("ALIGN", (1, 1), (-1, -1), "CENTER"),
        ("ALIGN", (0, 0), (0, -1), "LEFT"),
        ("INNERGRID", (0, 0), (-1, -1), 0.4, colors.HexColor("#C9CCDB")),
        ("BOX", (0, 0), (-1, -1), 0.6, colors.HexColor("#A4A8BB")),
    ]))
    return table


def insights_section(insights: List[Dict], styles) -> List:
    blocks: List = []
    if not insights:
        blocks.append(Paragraph("No se generaron insights automáticamente.", styles["Body"]))
        return blocks
    for idx, ins in enumerate(insights, start=1):
        title = Paragraph(f"{idx:02d}. {ins['title']}", styles["InsightTitle"])
        finding = Paragraph(f"<b>Finding:</b> {ins['finding']}", styles["InsightSub"])
        impact = Paragraph(f"<b>Impacto:</b> {ins['impact']}", styles["InsightSub"])
        rec = Paragraph(f"<b>Recomendación:</b> {ins['recommendation']}", styles["InsightSub"])
        blocks.append(KeepTogether([title, finding, impact, rec, Spacer(1, 0.2 * cm)]))
    return blocks


def glossary_section(styles) -> List:
    """Glossary of abbreviations and terms used in the report."""
    blocks: List = []
    terms = [
        ("ETA", "Estimated Time of Arrival — tiempo de entrega estimado en minutos que promete la app al usuario."),
        ("SLA", "Service Level Agreement — objetivo interno de tiempo de entrega (30 minutos en este análisis)."),
        ("Promo Hook", "Porcentaje de descuento visible en la tarjeta del restaurante dentro del feed de la app. Es lo primero que ve el usuario."),
        ("BM / Big Mac", "Combo Big Mac Mediano — producto benchmark para comparación de precios entre plataformas."),
        ("HDQ", "Hamburguesa Doble con Queso — segundo producto de referencia para comparar pricing."),
        ("CC", "Coca-Cola Mediana — tercer producto de referencia."),
        ("Delivery Fee", "Costo de envío que la plataforma cobra al usuario. Varía por zona y disponibilidad de repartidores."),
        ("Service Fee", "Comisión que cobra la plataforma sobre el subtotal. Estimado: Rappi 10%, Uber Eats 15%, DiDi Food 8%."),
        ("Total Estimado", "Subtotal de productos + delivery fee + service fee = lo que paga el usuario en checkout."),
        ("Wealthy / Non Wealthy", "Clasificación socioeconómica de la zona de entrega. Wealthy = zonas de alto poder adquisitivo."),
        ("CTR", "Click-Through Rate — tasa de clicks sobre impresiones en el feed de la app."),
    ]
    for term, definition in terms:
        blocks.append(Paragraph(f"<b>{term}:</b> {definition}", styles["GlossaryDef"]))
    return blocks


def chart_gallery_full(kpis: Dict, output_dir: Path, styles) -> List:
    """Include ALL charts with their descriptions and interpretations."""
    gallery: List = []
    chart_files = kpis.get("charts", [])  # No limit — include all charts
    for chart in chart_files:
        if not chart:
            continue
        path = output_dir / chart
        if not path.exists():
            continue

        stem = path.stem
        desc = CHART_DESCRIPTIONS.get(stem, {})
        chart_title = desc.get("title", stem.replace("_", " ").replace("chart ", "").title())
        purpose = desc.get("purpose", "")
        relevance = desc.get("relevance", "")

        elements = []
        elements.append(Paragraph(chart_title, styles["Section"]))

        if purpose:
            elements.append(Paragraph(f"<b>Qué muestra:</b> {purpose}", styles["ChartPurpose"]))
        if relevance:
            elements.append(Paragraph(f"<b>Relevancia para Strategy/Pricing:</b> {relevance}", styles["ChartRelevance"]))

        img = Image(str(path), width=15 * cm, height=8.5 * cm)
        elements.append(img)
        elements.append(Spacer(1, 0.4 * cm))

        gallery.append(KeepTogether(elements))
    return gallery


def build_story(kpis: Dict, insights: List[Dict], styles, chart_dir: Path) -> List:
    story: List = []
    story.append(PageBreak())  # content starts after cover

    # --- Glossary ---
    story.append(Paragraph("Glosario de términos y abreviaciones", styles["TitleSmall"]))
    story.append(HRFlowable(width="100%", thickness=1, color=ACCENT, spaceAfter=8))
    story.append(Paragraph(
        "Este informe usa las siguientes abreviaciones y métricas. Consulte esta sección si encuentra "
        "un término desconocido en los gráficos o tablas.",
        styles["Note"]
    ))
    story.append(Spacer(1, 0.2 * cm))
    story.extend(glossary_section(styles))
    story.append(Spacer(1, 0.4 * cm))

    # --- Executive summary ---
    meta = kpis.get("meta", {})
    summary_text = (
        f"Analizamos <b>{meta.get('addresses', 0)} direcciones</b> estratégicas en "
        f"<b>{len(meta.get('cities', []))} ciudades</b> ({', '.join(meta.get('cities', []))}). "
        f"El dataset se generó el {meta.get('generated_at', 'N/D')[:10]}. "
        "Las métricas excluyen registros con restaurant_available=False y status≠success para asegurar comparabilidad. "
        "Los productos monitoreados son: Combo Big Mac Mediano, Hamburguesa Doble con Queso, y Coca-Cola Mediana."
    )
    story.append(Paragraph("Resumen ejecutivo", styles["TitleSmall"]))
    story.append(HRFlowable(width="100%", thickness=1, color=RAPPI_RED, spaceAfter=8))
    story.append(Paragraph(summary_text, styles["Body"]))
    story.append(Spacer(1, 0.3 * cm))

    # --- KPI table (all metrics) ---
    story.append(Paragraph("Métricas comparativas por plataforma", styles["Section"]))
    story.append(Paragraph(
        "Tabla con todas las métricas clave promediadas por plataforma. Incluye los 3 productos, "
        "fees, tiempos y cobertura. Los valores N/D indican que el dato no estuvo disponible en ese scraping.",
        styles["Note"]
    ))
    story.append(platform_table(kpis, styles))
    story.append(Spacer(1, 0.4 * cm))

    # --- Wealthy vs Non Wealthy ---
    story.append(Paragraph("Variabilidad geográfica: Wealthy vs Non Wealthy", styles["Section"]))
    story.append(Paragraph(
        "Compara las métricas clave entre zonas de alto nivel socioeconómico (Wealthy: Polanco, Condesa, Santa Fe, etc.) "
        "y zonas populares (Non Wealthy: Iztapalapa, Ecatepec, Tepito, etc.). "
        "Si la competitividad varía por tipo de zona, los equipos de Pricing y Growth deben ajustar estrategias diferenciadas.",
        styles["Note"]
    ))
    story.append(wealthy_comparison_table(kpis, styles))
    story.append(Spacer(1, 0.4 * cm))

    # --- Availability ---
    story.append(Paragraph("Cobertura operacional (status report)", styles["Section"]))
    story.append(Paragraph(
        "Los casos con restaurant_available=False indican que la app no mostró el restaurante "
        "(posible restricción geográfica o bloqueo temporal). Los parciales pueden indicar menú incompleto.",
        styles["Note"]
    ))
    story.append(availability_table(kpis))

    # --- Top insights ---
    story.append(PageBreak())
    story.append(Paragraph("Top 5 Insights Accionables", styles["TitleSmall"]))
    story.append(HRFlowable(width="100%", thickness=1, color=RAPPI_RED, spaceAfter=8))
    story.append(Paragraph(
        "Cada insight incluye el hallazgo, su impacto en el negocio, y una recomendación concreta "
        "para los equipos de Strategy y Pricing.",
        styles["Note"]
    ))
    story.append(Spacer(1, 0.2 * cm))
    story.extend(insights_section(insights, styles))

    # --- All charts with descriptions ---
    story.append(PageBreak())
    story.append(Paragraph("Visualizaciones y análisis", styles["TitleSmall"]))
    story.append(HRFlowable(width="100%", thickness=1, color=RAPPI_RED, spaceAfter=8))
    story.append(Paragraph(
        "Cada gráfico incluye una explicación de qué muestra y por qué es relevante para la toma de decisiones. "
        "Todas las vistas se alimentan del CSV y detectan dinámicamente las plataformas disponibles.",
        styles["Note"]
    ))
    story.append(Spacer(1, 0.3 * cm))
    story.extend(chart_gallery_full(kpis, chart_dir, styles))
    return story


def main() -> None:
    parser = argparse.ArgumentParser(description="Genera el PDF ejecutivo de insights")
    parser.add_argument("--output", help="Ruta final del PDF", default=str(OUTPUT_PDF))
    args = parser.parse_args()

    output_dir = Path("output")
    kpis, insights = load_payloads(output_dir)
    styles = build_styles()

    doc = SimpleDocTemplate(
        args.output,
        pagesize=A4,
        leftMargin=MARGIN,
        rightMargin=MARGIN,
        topMargin=MARGIN,
        bottomMargin=2 * cm,
    )
    story = build_story(kpis, insights, styles, output_dir)
    doc.build(story, onFirstPage=cover_page, canvasmaker=NumberedCanvas)
    print(f"[OK] PDF generado -> {args.output}")


if __name__ == "__main__":
    main()
