"""
Informe Ejecutivo PDF -- Competitive Intelligence Rappi Mexico
Uso: python analysis/generate_report_pdf.py
     python analysis/generate_report_pdf.py --mock   (forzar datos mock)

Reads KPIs from output/kpis.json (generated by generate_analysis.py).
Falls back to mock values if kpis.json is not found.
"""

import json, os, argparse
from pathlib import Path
from datetime import datetime

from reportlab.lib.pagesizes import A4
from reportlab.lib import colors
from reportlab.lib.units import cm
from reportlab.platypus import (
    SimpleDocTemplate, Paragraph, Spacer, Image,
    Table, TableStyle, PageBreak, HRFlowable, KeepTogether
)
from reportlab.lib.styles import ParagraphStyle
from reportlab.lib.enums import TA_CENTER, TA_JUSTIFY
from reportlab.pdfgen import canvas as pdfcanvas

os.chdir(Path(__file__).parent.parent)

# -- Colors ---
RAPPI_RED  = colors.HexColor("#FF441F")
DARK       = colors.HexColor("#1A1A2E")
UBER_GRN   = colors.HexColor("#06C167")
DIDI_ORG   = colors.HexColor("#FF6B00")
LIGHT      = colors.HexColor("#F5F5F5")
MED_GRAY   = colors.HexColor("#CCCCCC")
DARK_GRAY  = colors.HexColor("#555555")
ACCENT     = colors.HexColor("#2E4057")

W, H = A4
MARGIN = 1.8*cm

PL = {"rappi": "Rappi", "ubereats": "Uber Eats", "didifood": "DiDi Food"}


# -- Styles ---
def make_styles():
    return {
        "h1": ParagraphStyle("h1", fontSize=16, leading=20, spaceBefore=14, spaceAfter=6,
            textColor=RAPPI_RED, fontName="Helvetica-Bold"),
        "h2": ParagraphStyle("h2", fontSize=12, leading=15, spaceBefore=12, spaceAfter=5,
            textColor=DARK, fontName="Helvetica-Bold"),
        "body": ParagraphStyle("body", fontSize=9.5, leading=13, spaceAfter=5,
            textColor=DARK_GRAY, alignment=TA_JUSTIFY),
        "caption": ParagraphStyle("cap", fontSize=7.5, leading=10, alignment=TA_CENTER,
            textColor=DARK_GRAY, fontName="Helvetica-Oblique", spaceAfter=8),
        "bullet": ParagraphStyle("bul", fontSize=9.5, leading=14, leftIndent=14,
            spaceAfter=2, textColor=DARK_GRAY),
    }


# -- Page numbering ---
class NumberedCanvas(pdfcanvas.Canvas):
    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        self._pages = []

    def showPage(self):
        self._pages.append(dict(self.__dict__))
        self._startPage()

    def save(self):
        n = len(self._pages)
        for state in self._pages:
            self.__dict__.update(state)
            if self._pageNumber > 1:
                self.setFont("Helvetica", 7.5)
                self.setFillColor(DARK_GRAY)
                self.drawRightString(W-MARGIN, 1.1*cm, f"Pag. {self._pageNumber}/{n}")
                self.drawString(MARGIN, 1.1*cm, "CONFIDENCIAL -- Competitive Intelligence Rappi Mexico")
                self.setStrokeColor(MED_GRAY)
                self.setLineWidth(0.4)
                self.line(MARGIN, 1.4*cm, W-MARGIN, 1.4*cm)
            super().showPage()
        super().save()


# -- Cover ---
def cover_page(canvas, doc):
    canvas.saveState()
    canvas.setFillColor(DARK)
    canvas.rect(0, 0, W, H, fill=1, stroke=0)
    canvas.setFillColor(RAPPI_RED)
    canvas.rect(0, H*0.62, W, H*0.38, fill=1, stroke=0)
    canvas.setFont("Helvetica-Bold", 36)
    canvas.setFillColor(colors.white)
    canvas.drawString(MARGIN, H-2.5*cm, "RAPPI")
    canvas.setFont("Helvetica-Bold", 26)
    canvas.drawString(MARGIN, H-4.5*cm, "Competitive Intelligence")
    canvas.setFont("Helvetica", 20)
    canvas.drawString(MARGIN, H-5.8*cm, "Rappi vs Uber Eats vs DiDi Food")
    canvas.setFont("Helvetica", 11)
    canvas.setFillColor(colors.HexColor("#FFCCBB"))
    canvas.drawString(MARGIN, H-7.5*cm, f"Mexico -- {datetime.now().strftime('%B %Y')}")
    canvas.setFillColor(colors.HexColor("#0D0D1F"))
    canvas.rect(0, 0, W, 5.5*cm, fill=1, stroke=0)
    canvas.setFont("Helvetica-Bold", 11)
    canvas.setFillColor(colors.white)
    canvas.drawString(MARGIN, 4*cm, "ENTREGABLE 2.2 -- Informe de Insights Competitivos")
    canvas.setFont("Helvetica", 10)
    canvas.setFillColor(colors.HexColor("#AAAAAA"))
    canvas.drawString(MARGIN, 2.8*cm, "McDonald's comparado en las 3 plataformas")
    canvas.drawString(MARGIN, 2.0*cm, "Combo Big Mac mediano | Hamburguesa doble con queso | Coca-Cola mediana")
    canvas.restoreState()


# -- KPI helpers ---
def fmt_price(v):
    if v is None or (isinstance(v, float) and v != v):
        return "N/D"
    return f"${v:.0f}"

def fmt_pct(v):
    if v is None or (isinstance(v, float) and v != v):
        return "N/D"
    return f"{v:.0f}%"

def fmt_num(v, suffix=""):
    if v is None or (isinstance(v, float) and v != v):
        return "N/D"
    return f"{v:.0f}{suffix}"

def fmt_rating(v):
    if v is None or (isinstance(v, float) and v != v):
        return "N/D"
    return f"{v:.1f}"

def fmt_reviews(v):
    """Format review count with thousands separator."""
    if v is None or (isinstance(v, float) and v != v):
        return "N/D"
    v = int(v)
    if v >= 1000:
        return f"{v:,}".replace(",", ".")
    return str(v)


def load_kpis():
    """Load KPIs from output/kpis.json or return empty dict."""
    p = Path("output/kpis.json")
    if p.exists():
        with open(p, encoding="utf-8") as f:
            return json.load(f)
    return {}


def build_kpi_table(kpis, plats):
    """Build strategic KPI table focused on pricing, promos, and engagement."""
    def val(plat, key):
        if plat not in kpis:
            return "N/D"
        v = kpis[plat].get(key)
        return v

    rows = [["Metrica"] + [PL.get(p, p) for p in plats]]
    rows.append(["Review count promedio"]            + [fmt_reviews(val(p, "review_count_avg")) for p in plats])
    rows.append(["Combo Big Mac (precio base)"]      + [fmt_price(val(p, "combo_orig_avg")) for p in plats])
    rows.append(["Combo Big Mac (descuento prom.)"]  + [fmt_pct(val(p, "combo_disc_pct_avg")) for p in plats])
    rows.append(["% zonas con descuento en Combo"]   + [fmt_pct(val(p, "combo_disc_zone_pct")) for p in plats])
    rows.append(["Promo general restaurante (hook %)"] + [fmt_pct(val(p, "promo_avg")) for p in plats])
    rows.append(["ETA promedio (min)"]               + [fmt_num(val(p, "eta_avg")) for p in plats])
    rows.append(["Rating McDonald's"]                + [fmt_rating(val(p, "rating_avg")) for p in plats])
    rows.append(["Service fee %"]                    + [fmt_pct(val(p, "service_fee_pct")) for p in plats])
    rows.append(["Total all-in promedio"]            + [fmt_price(val(p, "total_avg")) for p in plats])
    return rows


def generate_insights(kpis, plats):
    """Generate 5 strategic insights for Strategy/Pricing team."""
    insights = []

    # Helper to get a value safely
    def g(plat, key, default=0):
        if plat not in kpis:
            return default
        v = kpis[plat].get(key)
        return v if v is not None else default

    # ---- Insight 1: Market Engagement (review count as proxy) ----
    review_counts = {p: g(p, "review_count_avg") for p in plats}
    if "ubereats" in plats and "rappi" in plats:
        u_rev = review_counts.get("ubereats", 0)
        r_rev = review_counts.get("rappi", 0)
        d_rev = review_counts.get("didifood", 0)
        if r_rev > 0:
            ratio = u_rev / r_rev
        else:
            ratio = 0

        if ratio > 1:
            finding = (f"Uber Eats acumula ~{u_rev:,.0f} reviews promedio por restaurante vs "
                       f"~{r_rev:,.0f} de Rappi — una relacion de {ratio:.0f}x. "
                       f"DiDi Food muestra ~{d_rev:,.0f} reviews.")
        else:
            finding = (f"Rappi acumula ~{r_rev:,.0f} reviews promedio por restaurante vs "
                       f"~{u_rev:,.0f} de Uber Eats. DiDi Food muestra ~{d_rev:,.0f} reviews.")

        insights.append({
            "n": "01",
            "title": "Market Engagement: review count como proxy de volumen",
            "finding": finding,
            "impacto": ("El numero de reviews es un indicador indirecto de volumen de pedidos "
                        "y engagement de la base de usuarios. Una brecha de magnitud sugiere que "
                        "la competencia tiene mayor penetracion o mayor frecuencia de uso en "
                        "este vertical (QSR)."),
            "rec": ("Implementar campanas de incentivo de reviews (cupones post-pedido). "
                    "Evaluar si la brecha de engagement refleja menor share en QSR o menor "
                    "habito de resena en la base Rappi. Cruzar con datos internos de GMV."),
            "color": UBER_GRN,
        })

    # ---- Insight 2: Promotional Aggressiveness ----
    promos = {p: g(p, "promo_avg") for p in plats}
    combo_disc = {p: g(p, "combo_disc_pct_avg") for p in plats}
    active_promos = {p: v for p, v in promos.items() if v > 0}
    if len(active_promos) >= 2:
        most_aggressive = max(active_promos, key=active_promos.get)
        least_aggressive = min(active_promos, key=active_promos.get)
        insights.append({
            "n": "02",
            "title": (f"Agresividad Promocional: {PL[most_aggressive]} lidera, "
                      f"{PL[least_aggressive]} mas conservador"),
            "finding": (f"{PL[most_aggressive]} muestra descuentos hook de {promos[most_aggressive]:.0f}% "
                        f"en promedio, mientras que {PL[least_aggressive]} ofrece {promos[least_aggressive]:.0f}%. "
                        f"En descuentos directos al Combo Big Mac: "
                        f"{PL.get(most_aggressive, most_aggressive)} aplica {combo_disc.get(most_aggressive, 0):.0f}% "
                        f"vs {combo_disc.get(least_aggressive, 0):.0f}% de {PL.get(least_aggressive, least_aggressive)}."),
            "impacto": ("El descuento visible antes de entrar al restaurante (hook %) es el "
                        "principal driver de click-through en el feed. Una plataforma que aparece "
                        "menos atractiva pierde conversion en el top-of-funnel. El que subsidia "
                        "mas agresivamente esta comprando share a costa de margen."),
            "rec": ("Evaluar ROI de igualar la agresividad del lider en horarios de alta competencia "
                    "(12-14h, 19-21h). Considerar promos visibles pero de menor costo (ej. 2x1 en "
                    "productos de bajo margen) en lugar de descuentos directos. Monitorear si DiDi "
                    "esta quemando caja para ganar share o si tiene acuerdos con restaurantes."),
            "color": DIDI_ORG,
        })

    # ---- Insight 3: Price Parity ----
    combos = {p: g(p, "combo_orig_avg") for p in plats if g(p, "combo_orig_avg") > 0}
    if len(combos) >= 2:
        min_p, max_p = min(combos.values()), max(combos.values())
        diff_pct = (max_p / min_p - 1) * 100 if min_p > 0 else 0
        insights.append({
            "n": "03",
            "title": f"Paridad de Precios: variacion de solo ~{diff_pct:.0f}% entre plataformas",
            "finding": (f"El Combo Big Mac mediano oscila entre ${min_p:.0f} y ${max_p:.0f} MXN "
                        f"segun la plataforma — una variacion de ~{diff_pct:.0f}%. Los precios base "
                        f"de producto son esencialmente equivalentes porque McDonald's controla su "
                        f"pricing cross-platform. La guerra NO se libra en el precio de producto."),
            "impacto": ("Si los precios base son paritarios, el diferenciador real para el usuario "
                        "es la combinacion de: (1) descuentos/promos visibles, (2) fees totales "
                        "(service fee + delivery fee), y (3) velocidad de entrega. La estrategia "
                        "de pricing debe enfocarse en estos vectores, no en negociar precios con "
                        "el restaurante."),
            "rec": ("Comunicar al equipo de pricing que la palanca no esta en el precio de menu. "
                    "Enfocar la propuesta de valor en: total all-in mas bajo, promos agresivas en "
                    "momentos clave, y velocidad. Usar la paridad de precios como argumento "
                    "comercial con restaurantes ('no les pedimos bajar precio, nosotros subsidiamos')."),
            "color": ACCENT,
        })

    # ---- Insight 4: Geographic Strategy ----
    geo_insights = []
    for p in plats:
        total_w = g(p, "total_wealthy")
        total_nw = g(p, "total_non_wealthy")
        if total_w > 0 and total_nw > 0:
            geo_insights.append((p, total_w, total_nw))

    if len(geo_insights) >= 2:
        details = []
        for p, tw, tnw in geo_insights:
            diff = tnw - tw
            details.append(f"{PL[p]}: ${tw:.0f} (wealthy) vs ${tnw:.0f} (non-wealthy), delta ${diff:+.0f}")
        detail_str = ". ".join(details) + "."

        insights.append({
            "n": "04",
            "title": "Estrategia Geografica: variabilidad de precios wealthy vs non-wealthy",
            "finding": (f"El costo total all-in varia segun zona socioeconomica. {detail_str} "
                        f"Esto refleja diferencias en delivery fee y cobertura promocional "
                        f"por zona, no en precio de producto."),
            "impacto": ("Las zonas non-wealthy representan mayor volumen potencial pero menor "
                        "ticket promedio. La estructura de fees actual puede estar penalizando "
                        "la penetracion en zonas de alto crecimiento. Un competidor que subsidie "
                        "fees en estas zonas puede capturar share de forma desproporcionada."),
            "rec": ("Implementar pricing geografico diferenciado: reducir delivery fee en zonas "
                    "non-wealthy con alto potencial de crecimiento. Cruzar con datos internos "
                    "de densidad de repartidores y costo real de entrega por zona. Monitorear "
                    "si la competencia aplica subsidios diferenciados por zona."),
            "color": RAPPI_RED,
        })

    # ---- Insight 5: Operational (ETA + Rating) ----
    etas = {p: g(p, "eta_avg") for p in plats if g(p, "eta_avg") > 0}
    ratings = {p: g(p, "rating_avg") for p in plats if g(p, "rating_avg") > 0}
    if len(etas) >= 2 and len(ratings) >= 2:
        fastest = min(etas, key=etas.get)
        slowest = max(etas, key=etas.get)
        best_rated = max(ratings, key=ratings.get)
        eta_gap = etas[slowest] - etas[fastest]

        eta_details = ", ".join(f"{PL[p]}: {etas[p]:.0f} min" for p in plats if p in etas)
        rating_details = ", ".join(f"{PL[p]}: {ratings[p]:.1f}" for p in plats if p in ratings)

        insights.append({
            "n": "05",
            "title": f"Operacional: {PL[fastest]} lidera en ETA, {PL[best_rated]} en Rating",
            "finding": (f"ETAs promedio: {eta_details}. "
                        f"Ratings: {rating_details}. "
                        f"La diferencia maxima de ETA es de {eta_gap:.0f} minutos entre "
                        f"{PL[fastest]} y {PL[slowest]}."),
            "impacto": ("ETA es el segundo factor de decision despues del precio total. "
                        "Una diferencia de varios minutos es perceptible y afecta la "
                        "conversion, especialmente en horarios de alta demanda. El rating "
                        "refleja la experiencia acumulada del usuario y afecta la percepcion "
                        "de calidad de la plataforma."),
            "rec": ("Investigar si el gap de ETA es por densidad de repartidores o algoritmo "
                    "de routing. Si Rappi no lidera en ETA: aumentar incentivos de oferta en "
                    "horas pico y optimizar batching. Monitorear rating como leading indicator "
                    "de churn — una caida de 0.1 puntos puede correlacionar con perdida de "
                    "usuarios recurrentes."),
            "color": ACCENT,
        })

    return insights


# -- Build PDF ---
def build_pdf():
    kpis = load_kpis()
    plats = [p for p in ["rappi", "ubereats", "didifood"] if p in kpis]
    if not plats:
        plats = ["rappi", "ubereats", "didifood"]

    out = "output/Competitive_Intelligence_Rappi_MX.pdf"
    doc = SimpleDocTemplate(out, pagesize=A4,
        leftMargin=MARGIN, rightMargin=MARGIN,
        topMargin=MARGIN, bottomMargin=2*cm)
    s = make_styles()
    story = []

    # -- Cover --
    story.append(PageBreak())

    # -- Executive Summary --
    story.append(Paragraph("Resumen Ejecutivo", s["h1"]))
    story.append(HRFlowable(width="100%", thickness=1, color=RAPPI_RED, spaceAfter=8))

    n_plats = len(plats)
    plat_names = ", ".join(PL.get(p, p) for p in plats)
    story.append(Paragraph(
        f"Este informe analiza la posicion competitiva de Rappi frente a {plat_names} "
        f"en Mexico, con foco en posicionamiento de precios, estrategia promocional, "
        f"variabilidad geografica y engagement de mercado (review count como proxy de "
        f"volumen). El analisis compara McDonald's como restaurante de referencia en "
        f"las 3 plataformas. Los datos fueron recolectados mediante scraping automatizado "
        f"con Playwright.",
        s["body"]
    ))
    story.append(Spacer(1, 0.4*cm))

    # KPI table
    kpi_rows = build_kpi_table(kpis, plats)
    col_widths = [7.5*cm] + [max(3.0, 9.5/len(plats))*cm for _ in plats]
    kpi_table = Table(kpi_rows, colWidths=col_widths)

    plat_bg = {"rappi": colors.HexColor("#FFF0ED"), "ubereats": colors.HexColor("#EDF9F2"),
               "didifood": colors.HexColor("#FFF5ED")}
    style_cmds = [
        ("BACKGROUND", (0,0), (-1,0), RAPPI_RED),
        ("TEXTCOLOR",  (0,0), (-1,0), colors.white),
        ("FONTNAME",   (0,0), (-1,0), "Helvetica-Bold"),
        ("FONTSIZE",   (0,0), (-1,-1), 9),
        ("ALIGN",      (1,0), (-1,-1), "CENTER"),
        ("ALIGN",      (0,0), (0,-1), "LEFT"),
        ("BACKGROUND", (0,1), (0,-1), LIGHT),
        ("ROWBACKGROUNDS", (0,1), (-1,-1), [colors.white, LIGHT]),
        ("GRID",       (0,0), (-1,-1), 0.4, MED_GRAY),
        ("PADDING",    (0,0), (-1,-1), 6),
    ]
    for idx, p in enumerate(plats):
        bg = plat_bg.get(p, LIGHT)
        style_cmds.append(("BACKGROUND", (idx+1, 1), (idx+1, -1), bg))
    kpi_table.setStyle(TableStyle(style_cmds))
    story.append(kpi_table)
    story.append(PageBreak())

    # -- Top 5 Insights --
    story.append(Paragraph("Top 5 Insights Estrategicos", s["h1"]))
    story.append(HRFlowable(width="100%", thickness=1, color=RAPPI_RED, spaceAfter=10))

    insights = generate_insights(kpis, plats)
    for ins in insights:
        box_data = [[
            Paragraph(f"<b>INSIGHT {ins['n']}</b>",
                      ParagraphStyle("in", fontSize=9, textColor=colors.white, fontName="Helvetica-Bold")),
            Paragraph(ins["title"],
                      ParagraphStyle("it2", fontSize=9.5, textColor=colors.white,
                                     fontName="Helvetica-Bold", leading=12)),
        ]]
        box = Table(box_data, colWidths=[2.2*cm, 14.3*cm])
        box.setStyle(TableStyle([
            ("BACKGROUND", (0,0), (-1,-1), ins["color"]),
            ("PADDING",    (0,0), (-1,-1), 8),
            ("VALIGN",     (0,0), (-1,-1), "MIDDLE"),
        ]))
        story.append(box)

        detail_data = [
            ["Finding",       Paragraph(ins["finding"], s["body"])],
            ["Impacto",       Paragraph(ins["impacto"], s["body"])],
            ["Recomendacion", Paragraph(ins["rec"],     s["body"])],
        ]
        detail = Table(detail_data, colWidths=[2.8*cm, 13.7*cm])
        detail.setStyle(TableStyle([
            ("BACKGROUND", (0,0), (0,-1), LIGHT),
            ("FONTNAME",   (0,0), (0,-1), "Helvetica-Bold"),
            ("FONTSIZE",   (0,0), (-1,-1), 9),
            ("PADDING",    (0,0), (-1,-1), 7),
            ("VALIGN",     (0,0), (-1,-1), "TOP"),
            ("GRID",       (0,0), (-1,-1), 0.3, MED_GRAY),
        ]))
        story.append(detail)
        story.append(Spacer(1, 0.5*cm))

    story.append(PageBreak())

    # -- Charts --
    story.append(Paragraph("Analisis Visual", s["h1"]))
    story.append(HRFlowable(width="100%", thickness=1, color=RAPPI_RED, spaceAfter=8))

    charts = [
        ("output/chart1_delivery_fee.png",   "Fig. 1 -- Posicionamiento de precios"),
        ("output/chart2_eta_rating.png",     "Fig. 2 -- Operacional (ETA, Rating, Engagement)"),
        ("output/chart3_product_prices.png", "Fig. 3 -- Profundidad de descuentos"),
        ("output/chart4_fee_structure.png",  "Fig. 4 -- Estrategia Promocional"),
        ("output/chart5_promotions.png",     "Fig. 5 -- Competitividad Geografica"),
        ("output/chart6_geo_heatmap.png",    "Fig. 6 -- Engagement de mercado"),
        ("output/chart7_radar.png",          "Fig. 7 -- Posicionamiento multidimensional"),
    ]

    for path, caption in charts:
        if Path(path).exists():
            img = Image(path, width=W-2*MARGIN, height=(W-2*MARGIN)*0.38)
            story.append(img)
            story.append(Paragraph(caption, s["caption"]))
            story.append(Spacer(1, 0.3*cm))

    story.append(PageBreak())

    # -- Methodology --
    story.append(Paragraph("Metodologia y Limitaciones", s["h1"]))
    story.append(HRFlowable(width="100%", thickness=1, color=RAPPI_RED, spaceAfter=8))

    story.append(Paragraph("<b>Scope del analisis:</b>", s["h2"]))
    for item in [
        "Zonas representativas en CDMX, Guadalajara, Monterrey (wealthy + non-wealthy)",
        "Restaurante de referencia: McDonald's (presente en las 3 plataformas)",
        "Productos: Combo Big Mac mediano, Hamburguesa doble con queso, Coca-Cola mediana",
        "Scraping automatizado con Playwright + emulacion iPhone para DiDi Food",
        "Precio total = subtotal + delivery fee + (subtotal x service fee rate estimado)",
    ]:
        story.append(Paragraph(f"  {item}", s["bullet"]))

    story.append(Paragraph("<b>Limitaciones conocidas:</b>", s["h2"]))
    for item in [
        "Los datos representan un snapshot temporal -- precios y ETAs varian por hora y dia",
        "Service fee no siempre visible antes del checkout -- se usa tasa modal conocida",
        "DiDi Food tiene menor cobertura que Rappi y Uber Eats en zonas perifericas",
        "Review count puede variar segun la ventana de tiempo que muestra cada plataforma",
        "Para produccion: usar proxies residenciales para Uber Eats (Cloudflare activo)",
    ]:
        story.append(Paragraph(f"  {item}", s["bullet"]))

    story.append(Paragraph("<b>Next steps sugeridos:</b>", s["h2"]))
    for item in [
        "Automatizar scraping diario (cron job / GitHub Actions) para tracking temporal",
        "Expandir a verticales: retail y farmacia",
        "Integrar datos internos de Rappi (GMV por zona, churn rate) para cruzar con review counts",
        "Implementar alertas automaticas cuando competidor lance promo > 30%",
        "Segmentar analisis por horario (almuerzo vs cena) para detectar patrones promocionales",
    ]:
        story.append(Paragraph(f"  {item}", s["bullet"]))

    # -- Build --
    doc.build(story, onFirstPage=cover_page, canvasmaker=NumberedCanvas)
    print(f"  [ok] PDF -> {out}")
    return out


if __name__ == "__main__":
    build_pdf()
