"""
Informe Ejecutivo PDF -- Competitive Intelligence Rappi Mexico
Uso: python analysis/generate_report_pdf.py
     python analysis/generate_report_pdf.py --mock   (forzar datos mock)

Reads KPIs from output/kpis.json (generated by generate_analysis.py).
Falls back to mock values if kpis.json is not found.
"""

import json, os, argparse
from pathlib import Path
from datetime import datetime

from reportlab.lib.pagesizes import A4
from reportlab.lib import colors
from reportlab.lib.units import cm
from reportlab.platypus import (
    SimpleDocTemplate, Paragraph, Spacer, Image,
    Table, TableStyle, PageBreak, HRFlowable, KeepTogether
)
from reportlab.lib.styles import ParagraphStyle
from reportlab.lib.enums import TA_CENTER, TA_JUSTIFY
from reportlab.pdfgen import canvas as pdfcanvas

os.chdir(Path(__file__).parent.parent)

# -- Colors ---
RAPPI_RED  = colors.HexColor("#FF441F")
DARK       = colors.HexColor("#1A1A2E")
UBER_GRN   = colors.HexColor("#06C167")
DIDI_ORG   = colors.HexColor("#FF6B00")
LIGHT      = colors.HexColor("#F5F5F5")
MED_GRAY   = colors.HexColor("#CCCCCC")
DARK_GRAY  = colors.HexColor("#555555")
ACCENT     = colors.HexColor("#2E4057")

W, H = A4
MARGIN = 1.8*cm

PL = {"rappi": "Rappi", "ubereats": "Uber Eats", "didifood": "DiDi Food"}


# -- Styles ---
def make_styles():
    return {
        "h1": ParagraphStyle("h1", fontSize=16, leading=20, spaceBefore=14, spaceAfter=6,
            textColor=RAPPI_RED, fontName="Helvetica-Bold"),
        "h2": ParagraphStyle("h2", fontSize=12, leading=15, spaceBefore=12, spaceAfter=5,
            textColor=DARK, fontName="Helvetica-Bold"),
        "body": ParagraphStyle("body", fontSize=9.5, leading=13, spaceAfter=5,
            textColor=DARK_GRAY, alignment=TA_JUSTIFY),
        "caption": ParagraphStyle("cap", fontSize=7.5, leading=10, alignment=TA_CENTER,
            textColor=DARK_GRAY, fontName="Helvetica-Oblique", spaceAfter=8),
        "bullet": ParagraphStyle("bul", fontSize=9.5, leading=14, leftIndent=14,
            spaceAfter=2, textColor=DARK_GRAY),
    }


# -- Page numbering ---
class NumberedCanvas(pdfcanvas.Canvas):
    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        self._pages = []

    def showPage(self):
        self._pages.append(dict(self.__dict__))
        self._startPage()

    def save(self):
        n = len(self._pages)
        for state in self._pages:
            self.__dict__.update(state)
            if self._pageNumber > 1:
                self.setFont("Helvetica", 7.5)
                self.setFillColor(DARK_GRAY)
                self.drawRightString(W-MARGIN, 1.1*cm, f"Pag. {self._pageNumber}/{n}")
                self.drawString(MARGIN, 1.1*cm, "CONFIDENCIAL -- Competitive Intelligence Rappi Mexico")
                self.setStrokeColor(MED_GRAY)
                self.setLineWidth(0.4)
                self.line(MARGIN, 1.4*cm, W-MARGIN, 1.4*cm)
            super().showPage()
        super().save()


# -- Cover ---
def cover_page(canvas, doc):
    canvas.saveState()
    canvas.setFillColor(DARK)
    canvas.rect(0, 0, W, H, fill=1, stroke=0)
    canvas.setFillColor(RAPPI_RED)
    canvas.rect(0, H*0.62, W, H*0.38, fill=1, stroke=0)
    canvas.setFont("Helvetica-Bold", 36)
    canvas.setFillColor(colors.white)
    canvas.drawString(MARGIN, H-2.5*cm, "RAPPI")
    canvas.setFont("Helvetica-Bold", 26)
    canvas.drawString(MARGIN, H-4.5*cm, "Competitive Intelligence")
    canvas.setFont("Helvetica", 20)
    canvas.drawString(MARGIN, H-5.8*cm, "Rappi vs Uber Eats vs DiDi Food")
    canvas.setFont("Helvetica", 11)
    canvas.setFillColor(colors.HexColor("#FFCCBB"))
    canvas.drawString(MARGIN, H-7.5*cm, f"Mexico -- {datetime.now().strftime('%B %Y')}")
    canvas.setFillColor(colors.HexColor("#0D0D1F"))
    canvas.rect(0, 0, W, 5.5*cm, fill=1, stroke=0)
    canvas.setFont("Helvetica-Bold", 11)
    canvas.setFillColor(colors.white)
    canvas.drawString(MARGIN, 4*cm, "ENTREGABLE 2.2 -- Informe de Insights Competitivos")
    canvas.setFont("Helvetica", 10)
    canvas.setFillColor(colors.HexColor("#AAAAAA"))
    canvas.drawString(MARGIN, 2.8*cm, "McDonald's comparado en las 3 plataformas")
    canvas.drawString(MARGIN, 2.0*cm, "Combo Big Mac mediano | Hamburguesa doble con queso | Coca-Cola mediana")
    canvas.restoreState()


# -- KPI helpers ---
def fmt_price(v):
    if v is None or (isinstance(v, float) and v != v):
        return "N/D"
    return f"${v:.0f}"

def fmt_pct(v):
    if v is None or (isinstance(v, float) and v != v):
        return "N/D"
    return f"{v:.0f}%"

def fmt_num(v, suffix=""):
    if v is None or (isinstance(v, float) and v != v):
        return "N/D"
    return f"{v:.0f}{suffix}"

def fmt_rating(v):
    if v is None or (isinstance(v, float) and v != v):
        return "N/D"
    return f"{v:.1f}"


def load_kpis():
    """Load KPIs from output/kpis.json or return empty dict."""
    p = Path("output/kpis.json")
    if p.exists():
        with open(p, encoding="utf-8") as f:
            return json.load(f)
    return {}


def build_kpi_table(kpis, plats):
    """Build dynamic KPI table from computed data."""
    def val(plat, key):
        if plat not in kpis:
            return "N/D"
        v = kpis[plat].get(key)
        return v

    rows = [["Metrica"] + [PL.get(p, p) for p in plats]]
    rows.append(["Delivery fee promedio (MXN)"] + [fmt_price(val(p, "delivery_fee_avg")) for p in plats])
    rows.append(["Delivery fee Wealthy (MXN)"] + [fmt_price(val(p, "delivery_fee_wealthy")) for p in plats])
    rows.append(["Delivery fee Non-Wealthy (MXN)"] + [fmt_price(val(p, "delivery_fee_non_wealthy")) for p in plats])
    rows.append(["ETA promedio (min)"] + [fmt_num(val(p, "eta_avg")) for p in plats])
    rows.append(["Service fee estimado"] + [fmt_pct(val(p, "service_fee_pct")) for p in plats])
    rows.append(["Promo general restaurante"] + [fmt_pct(val(p, "promo_avg")) for p in plats])
    rows.append(["Combo Big Mac (precio base)"] + [fmt_price(val(p, "combo_orig_avg")) for p in plats])
    rows.append(["Total all-in promedio"] + [fmt_price(val(p, "total_avg")) for p in plats])
    rows.append(["Rating McDonald's"] + [fmt_rating(val(p, "rating_avg")) for p in plats])
    return rows


def generate_insights(kpis, plats):
    """Generate dynamic insights based on actual KPIs."""
    insights = []

    # Helper to get a value safely
    def g(plat, key, default=0):
        if plat not in kpis:
            return default
        v = kpis[plat].get(key)
        return v if v is not None else default

    # Insight 1: Delivery fee comparison
    if "rappi" in plats and "ubereats" in plats:
        r_fee = g("rappi", "delivery_fee_avg")
        u_fee = g("ubereats", "delivery_fee_avg")
        if u_fee > 0:
            gap = (r_fee / u_fee - 1) * 100
        else:
            gap = 0
        if gap > 5:
            finding = (f"Rappi cobra en promedio ${r_fee:.0f} MXN de delivery fee vs "
                       f"${u_fee:.0f} MXN de Uber Eats — un {gap:.0f}% mas caro.")
            rec = ("Implementar pricing dinamico de delivery fee por zona. "
                   "Subsidiar fee en zonas perifericas con mayor potencial de crecimiento.")
        elif gap < -5:
            finding = (f"Rappi cobra en promedio ${r_fee:.0f} MXN de delivery fee vs "
                       f"${u_fee:.0f} MXN de Uber Eats — un {abs(gap):.0f}% mas barato.")
            rec = "Mantener la ventaja competitiva en delivery fee como diferenciador."
        else:
            finding = (f"Rappi y Uber Eats tienen delivery fees similares: "
                       f"${r_fee:.0f} vs ${u_fee:.0f} MXN.")
            rec = "El delivery fee no es un diferenciador — enfocar en velocidad y promos."

        insights.append({
            "n": "01",
            "title": f"Delivery Fee: Rappi ${r_fee:.0f} vs Uber Eats ${u_fee:.0f}",
            "finding": finding,
            "impacto": ("El delivery fee es una de las primeras cosas que ve el usuario. "
                        "Un fee mas alto puede reducir conversion en el momento de checkout."),
            "rec": rec,
            "color": RAPPI_RED,
        })

    # Insight 2: ETA comparison
    etas = {p: g(p, "eta_avg") for p in plats}
    fastest = min(plats, key=lambda p: etas[p]) if plats else None
    if fastest and len(plats) >= 2:
        others = [p for p in plats if p != fastest]
        avg_others = sum(etas[p] for p in others) / len(others) if others else 0
        gap_min = avg_others - etas[fastest]
        insights.append({
            "n": "02",
            "title": f"ETA: {PL[fastest]} es el mas rapido ({etas[fastest]:.0f} min promedio)",
            "finding": (f"{PL[fastest]} muestra ETA promedio de {etas[fastest]:.0f} min vs "
                        f"{avg_others:.0f} min promedio de la competencia. "
                        f"Diferencia de {gap_min:.0f} minutos."),
            "impacto": ("El ETA es el segundo factor de eleccion de plataforma despues del precio. "
                        "Una diferencia de minutos es perceptible y afecta la conversion."),
            "rec": ("Investigar si el gap es de densidad de repartidores o de algoritmo de routing. "
                    "Si es densidad: aumentar incentivos de oferta en horas pico."),
            "color": ACCENT,
        })

    # Insight 3: Price comparison
    combos = {p: g(p, "combo_orig_avg") for p in plats if g(p, "combo_orig_avg") > 0}
    if len(combos) >= 2:
        min_p, max_p = min(combos.values()), max(combos.values())
        diff_pct = (max_p / min_p - 1) * 100 if min_p > 0 else 0
        insights.append({
            "n": "03",
            "title": f"Precios de producto comparables entre plataformas (~{diff_pct:.0f}% variacion)",
            "finding": (f"El Combo Big Mac mediano cuesta entre ${min_p:.0f} y ${max_p:.0f} MXN "
                        f"segun la plataforma. La guerra NO es en precio de producto."),
            "impacto": ("El diferenciador real esta en la combinacion de fees + promos + velocidad. "
                        "Los descuentos por producto son el unico vector de diferenciacion."),
            "rec": ("Enfocar la propuesta de valor en fees + velocidad, no en precio de producto. "
                    "Usar los descuentos por producto como tactica de conversion en horarios de baja demanda."),
            "color": UBER_GRN,
        })

    # Insight 4: Fee structure / total
    totals = {p: g(p, "total_avg") for p in plats if g(p, "total_avg") > 0}
    if len(totals) >= 2:
        cheapest = min(totals, key=totals.get)
        most_exp = max(totals, key=totals.get)
        insights.append({
            "n": "04",
            "title": f"Costo total all-in: {PL[cheapest]} es el mas economico (${totals[cheapest]:.0f})",
            "finding": (f"{PL[cheapest]} tiene el menor costo total estimado (${totals[cheapest]:.0f} MXN) "
                        f"vs {PL[most_exp]} (${totals[most_exp]:.0f} MXN). "
                        f"La diferencia es de ${totals[most_exp]-totals[cheapest]:.0f} MXN."),
            "impacto": ("El costo total all-in es lo que realmente paga el usuario. "
                        "La percepcion de 'caro' vs 'barato' depende de esta suma final."),
            "rec": ("Evaluar ajustar la estructura de fees para competir en costo total. "
                    "El impacto en margen puede compensarse con mayor volumen."),
            "color": DIDI_ORG,
        })

    # Insight 5: Promotions
    promos = {p: g(p, "promo_avg") for p in plats if g(p, "promo_avg") > 0}
    if len(promos) >= 2:
        most_aggressive = max(promos, key=promos.get)
        least_aggressive = min(promos, key=promos.get)
        insights.append({
            "n": "05",
            "title": (f"Promos: {PL[most_aggressive]} es el mas agresivo "
                      f"({promos[most_aggressive]:.0f}% vs {promos[least_aggressive]:.0f}% de {PL[least_aggressive]})"),
            "finding": (f"{PL[most_aggressive]} muestra descuentos de hasta {promos[most_aggressive]:.0f}% "
                        f"en promedio, mientras que {PL[least_aggressive]} muestra {promos[least_aggressive]:.0f}%. "),
            "impacto": ("El 'hook' inicial (% descuento visible antes de entrar al restaurante) "
                        "influye directamente en la tasa de click. Aparecer menos atractivo "
                        "puede reducir la conversion."),
            "rec": ("Aumentar la agresividad promocional en el top-of-funnel. "
                    "Implementar promos visibles en horario 12-14hs cuando la competencia "
                    "por pedidos de almuerzo es maxima."),
            "color": RAPPI_RED,
        })

    return insights


# -- Build PDF ---
def build_pdf():
    kpis = load_kpis()
    plats = [p for p in ["rappi", "ubereats", "didifood"] if p in kpis]
    if not plats:
        plats = ["rappi", "ubereats", "didifood"]

    out = "output/Competitive_Intelligence_Rappi_MX.pdf"
    doc = SimpleDocTemplate(out, pagesize=A4,
        leftMargin=MARGIN, rightMargin=MARGIN,
        topMargin=MARGIN, bottomMargin=2*cm)
    s = make_styles()
    story = []

    # -- Cover --
    story.append(PageBreak())

    # -- Executive Summary --
    story.append(Paragraph("Resumen Ejecutivo", s["h1"]))
    story.append(HRFlowable(width="100%", thickness=1, color=RAPPI_RED, spaceAfter=8))

    n_plats = len(plats)
    plat_names = ", ".join(PL.get(p, p) for p in plats)
    story.append(Paragraph(
        f"Este informe analiza la posicion competitiva de Rappi frente a {plat_names} "
        f"en Mexico. El analisis compara precios de productos de referencia en McDonald's, "
        f"estructura de fees, tiempos de entrega, estrategia promocional y variabilidad geografica. "
        f"Los datos fueron recolectados mediante scraping automatizado con Playwright.",
        s["body"]
    ))
    story.append(Spacer(1, 0.4*cm))

    # KPI table
    kpi_rows = build_kpi_table(kpis, plats)
    col_widths = [6.5*cm] + [max(3.0, 10.5/len(plats))*cm for _ in plats]
    kpi_table = Table(kpi_rows, colWidths=col_widths)

    plat_bg = {"rappi": colors.HexColor("#FFF0ED"), "ubereats": colors.HexColor("#EDF9F2"),
               "didifood": colors.HexColor("#FFF5ED")}
    style_cmds = [
        ("BACKGROUND", (0,0), (-1,0), RAPPI_RED),
        ("TEXTCOLOR",  (0,0), (-1,0), colors.white),
        ("FONTNAME",   (0,0), (-1,0), "Helvetica-Bold"),
        ("FONTSIZE",   (0,0), (-1,-1), 9),
        ("ALIGN",      (1,0), (-1,-1), "CENTER"),
        ("ALIGN",      (0,0), (0,-1), "LEFT"),
        ("BACKGROUND", (0,1), (0,-1), LIGHT),
        ("ROWBACKGROUNDS", (0,1), (-1,-1), [colors.white, LIGHT]),
        ("GRID",       (0,0), (-1,-1), 0.4, MED_GRAY),
        ("PADDING",    (0,0), (-1,-1), 6),
    ]
    for idx, p in enumerate(plats):
        bg = plat_bg.get(p, LIGHT)
        style_cmds.append(("BACKGROUND", (idx+1, 1), (idx+1, -1), bg))
    kpi_table.setStyle(TableStyle(style_cmds))
    story.append(kpi_table)
    story.append(PageBreak())

    # -- Top 5 Insights --
    story.append(Paragraph("Top 5 Insights Accionables", s["h1"]))
    story.append(HRFlowable(width="100%", thickness=1, color=RAPPI_RED, spaceAfter=10))

    insights = generate_insights(kpis, plats)
    for ins in insights:
        box_data = [[
            Paragraph(f"<b>INSIGHT {ins['n']}</b>",
                      ParagraphStyle("in", fontSize=9, textColor=colors.white, fontName="Helvetica-Bold")),
            Paragraph(ins["title"],
                      ParagraphStyle("it2", fontSize=9.5, textColor=colors.white,
                                     fontName="Helvetica-Bold", leading=12)),
        ]]
        box = Table(box_data, colWidths=[2.2*cm, 14.3*cm])
        box.setStyle(TableStyle([
            ("BACKGROUND", (0,0), (-1,-1), ins["color"]),
            ("PADDING",    (0,0), (-1,-1), 8),
            ("VALIGN",     (0,0), (-1,-1), "MIDDLE"),
        ]))
        story.append(box)

        detail_data = [
            ["Finding",       Paragraph(ins["finding"], s["body"])],
            ["Impacto",       Paragraph(ins["impacto"], s["body"])],
            ["Recomendacion", Paragraph(ins["rec"],     s["body"])],
        ]
        detail = Table(detail_data, colWidths=[2.8*cm, 13.7*cm])
        detail.setStyle(TableStyle([
            ("BACKGROUND", (0,0), (0,-1), LIGHT),
            ("FONTNAME",   (0,0), (0,-1), "Helvetica-Bold"),
            ("FONTSIZE",   (0,0), (-1,-1), 9),
            ("PADDING",    (0,0), (-1,-1), 7),
            ("VALIGN",     (0,0), (-1,-1), "TOP"),
            ("GRID",       (0,0), (-1,-1), 0.3, MED_GRAY),
        ]))
        story.append(detail)
        story.append(Spacer(1, 0.5*cm))

    story.append(PageBreak())

    # -- Charts --
    story.append(Paragraph("Analisis Visual", s["h1"]))
    story.append(HRFlowable(width="100%", thickness=1, color=RAPPI_RED, spaceAfter=8))

    charts = [
        ("output/chart1_delivery_fee.png",   "Fig. 1 -- Delivery Fee por zona"),
        ("output/chart2_eta_rating.png",     "Fig. 2 -- ETA y Rating"),
        ("output/chart3_product_prices.png", "Fig. 3 -- Precios de producto"),
        ("output/chart4_fee_structure.png",  "Fig. 4 -- Estructura de fees"),
        ("output/chart5_promotions.png",     "Fig. 5 -- Estrategia promocional"),
        ("output/chart6_geo_heatmap.png",    "Fig. 6 -- Variabilidad geografica"),
        ("output/chart7_radar.png",          "Fig. 7 -- Posicionamiento multidimensional"),
    ]

    for path, caption in charts:
        if Path(path).exists():
            img = Image(path, width=W-2*MARGIN, height=(W-2*MARGIN)*0.38)
            story.append(img)
            story.append(Paragraph(caption, s["caption"]))
            story.append(Spacer(1, 0.3*cm))

    story.append(PageBreak())

    # -- Methodology --
    story.append(Paragraph("Metodologia y Limitaciones", s["h1"]))
    story.append(HRFlowable(width="100%", thickness=1, color=RAPPI_RED, spaceAfter=8))

    story.append(Paragraph("<b>Scope del analisis:</b>", s["h2"]))
    for item in [
        "Zonas representativas en CDMX, Guadalajara, Monterrey (wealthy + non-wealthy)",
        "Restaurante de referencia: McDonald's (presente en las 3 plataformas)",
        "Productos: Combo Big Mac mediano, Hamburguesa doble con queso, Coca-Cola mediana",
        "Scraping automatizado con Playwright + emulacion iPhone para DiDi Food",
        "Precio total = subtotal + delivery fee + (subtotal x service fee rate estimado)",
    ]:
        story.append(Paragraph(f"  {item}", s["bullet"]))

    story.append(Paragraph("<b>Limitaciones conocidas:</b>", s["h2"]))
    for item in [
        "Los datos representan un snapshot temporal — precios y ETAs varian por hora y dia",
        "Service fee no siempre visible antes del checkout — se usa tasa modal conocida",
        "DiDi Food tiene menor cobertura que Rappi y Uber Eats en zonas perifericas",
        "Para produccion: usar proxies residenciales para Uber Eats (Cloudflare activo)",
    ]:
        story.append(Paragraph(f"  {item}", s["bullet"]))

    story.append(Paragraph("<b>Next steps sugeridos:</b>", s["h2"]))
    for item in [
        "Automatizar scraping diario (cron job / GitHub Actions) para tracking temporal",
        "Expandir a verticales: retail y farmacia",
        "Integrar datos internos de Rappi (GMV por zona, churn rate)",
        "Implementar alertas automaticas cuando competidor lance promo > 30%",
    ]:
        story.append(Paragraph(f"  {item}", s["bullet"]))

    # -- Build --
    doc.build(story, onFirstPage=cover_page, canvasmaker=NumberedCanvas)
    print(f"  [ok] PDF -> {out}")
    return out


if __name__ == "__main__":
    build_pdf()
